# Generated by Django 6.0.3 on 2026-03-23 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0002_vehicle_description_vehicle_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('purchase', 'Buy a car'), ('rental', 'Rent a car')], max_length=10, verbose_name='Type')),
                ('status', models.CharField(choices=[('pending', 'Awaiting processing'), ('reviewing', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Reason for refusal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission date')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vehicles.vehicle')),
            ],
        ),
    ]
