# Generated by Django 6.0.3 on 2026-03-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rental_duration',
            field=models.IntegerField(blank=True, choices=[(12, '12 months'), (24, '24 months'), (
                36, '36 months'), (48, '48 months')], null=True, verbose_name='Rental duration (months)'),
        ),
    ]
