# Generated by Django 6.0.3 on 2026-03-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_document'),
        ('vehicles', '0003_rentaloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rental_options',
            field=models.ManyToManyField(blank=True, related_name='applications', to='vehicles.rentaloption'),
        ),
    ]
