# Generated by Django 6.0.3 on 2026-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('year', models.PositiveIntegerField(verbose_name='Year')),
                ('mileage', models.PositiveIntegerField(verbose_name='Mileage (km)')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (€)')),
            ],
        ),
    ]
