# Generated by Django 6.0.3 on 2026-03-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='monthly_rental',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8,
                                      null=True, verbose_name='Monthly fee (€/month)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('sale', 'For sale'), ('rental', 'To rent'),
                                   ('both', 'Buy or rent')], default='both', max_length=10, verbose_name='Offer type'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Price (€)'),
        ),
    ]
