# Generated by Django 6.0.3 on 2026-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_description_vehicle_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monthly price (€)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
